package com.edu.cn.mybatis.pojo;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.CID
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.CNID
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    private Integer cnid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.CCONTENT
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    private String ccontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.CDATE
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    private Date cdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.CIP
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    private String cip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.CAUTHOR
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    private String cauthor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.CID
     *
     * @return the value of comments.CID
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.CID
     *
     * @param cid the value for comments.CID
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.CNID
     *
     * @return the value of comments.CNID
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public Integer getCnid() {
        return cnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.CNID
     *
     * @param cnid the value for comments.CNID
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public void setCnid(Integer cnid) {
        this.cnid = cnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.CCONTENT
     *
     * @return the value of comments.CCONTENT
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public String getCcontent() {
        return ccontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.CCONTENT
     *
     * @param ccontent the value for comments.CCONTENT
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public void setCcontent(String ccontent) {
        this.ccontent = ccontent == null ? null : ccontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.CDATE
     *
     * @return the value of comments.CDATE
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public Date getCdate() {
        return cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.CDATE
     *
     * @param cdate the value for comments.CDATE
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public void setCdate(Date cdate) {
        this.cdate = cdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.CIP
     *
     * @return the value of comments.CIP
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public String getCip() {
        return cip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.CIP
     *
     * @param cip the value for comments.CIP
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public void setCip(String cip) {
        this.cip = cip == null ? null : cip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.CAUTHOR
     *
     * @return the value of comments.CAUTHOR
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public String getCauthor() {
        return cauthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.CAUTHOR
     *
     * @param cauthor the value for comments.CAUTHOR
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public void setCauthor(String cauthor) {
        this.cauthor = cauthor == null ? null : cauthor.trim();
    }
}