package com.edu.cn.mybatis.pojo;

import java.util.Date;
import java.util.List;

public class News {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.NID
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    private Integer nid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.NTID
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
//    private Integer ntid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.NTITLE
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
//    private String ntitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.NAUTHOR
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    private String nauthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.NCREATEDATE
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    private Date ncreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.NPICPATH
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    private String npicpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.NMODIFYDATE
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    private Date nmodifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.NSUMMARY
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    private String nsummary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.NCONTENT
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    private String ncontent;



    private List<Comment> comments;//新闻评论


    public News(Integer nid, String nauthor, Date ncreatedate, String npicpath, Date nmodifydate, String nsummary, String ncontent, List<Comment> comments) {
        this.nid = nid;
        this.nauthor = nauthor;
        this.ncreatedate = ncreatedate;
        this.npicpath = npicpath;
        this.nmodifydate = nmodifydate;
        this.nsummary = nsummary;
        this.ncontent = ncontent;
        this.comments = comments;
    }

    public News() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.NID
     *
     * @return the value of news.NID
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public Integer getNid() {
        return nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.NID
     *
     * @param nid the value for news.NID
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public void setNid(Integer nid) {
        this.nid = nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.NTID
     *
     * @return the value of news.NTID
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
//    public Integer getNtid() {
//        return ntid;
//    }

    public List<Comment> getComments() {
        return comments;
    }

    public void setComments(List<Comment> comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.NTID
     *
     * @param ntid the value for news.NTID
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
//    public void setNtid(Integer ntid) {
//        this.ntid = ntid;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.NTITLE
     *
     * @return the value of news.NTITLE
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
//    public String getNtitle() {
//        return ntitle;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.NTITLE
     *
     * @param ntitle the value for news.NTITLE
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
//    public void setNtitle(String ntitle) {
//        this.ntitle = ntitle == null ? null : ntitle.trim();
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.NAUTHOR
     *
     * @return the value of news.NAUTHOR
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public String getNauthor() {
        return nauthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.NAUTHOR
     *
     * @param nauthor the value for news.NAUTHOR
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public void setNauthor(String nauthor) {
        this.nauthor = nauthor == null ? null : nauthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.NCREATEDATE
     *
     * @return the value of news.NCREATEDATE
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public Date getNcreatedate() {
        return ncreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.NCREATEDATE
     *
     * @param ncreatedate the value for news.NCREATEDATE
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public void setNcreatedate(Date ncreatedate) {
        this.ncreatedate = ncreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.NPICPATH
     *
     * @return the value of news.NPICPATH
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public String getNpicpath() {
        return npicpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.NPICPATH
     *
     * @param npicpath the value for news.NPICPATH
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public void setNpicpath(String npicpath) {
        this.npicpath = npicpath == null ? null : npicpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.NMODIFYDATE
     *
     * @return the value of news.NMODIFYDATE
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public Date getNmodifydate() {
        return nmodifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.NMODIFYDATE
     *
     * @param nmodifydate the value for news.NMODIFYDATE
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public void setNmodifydate(Date nmodifydate) {
        this.nmodifydate = nmodifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.NSUMMARY
     *
     * @return the value of news.NSUMMARY
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public String getNsummary() {
        return nsummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.NSUMMARY
     *
     * @param nsummary the value for news.NSUMMARY
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public void setNsummary(String nsummary) {
        this.nsummary = nsummary == null ? null : nsummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.NCONTENT
     *
     * @return the value of news.NCONTENT
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public String getNcontent() {
        return ncontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.NCONTENT
     *
     * @param ncontent the value for news.NCONTENT
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public void setNcontent(String ncontent) {
        this.ncontent = ncontent == null ? null : ncontent.trim();
    }

    @Override
    public String toString() {
        return "News{" +
                "nid=" + nid +
                ", nauthor='" + nauthor + '\'' +
                ", ncreatedate=" + ncreatedate +
                ", npicpath='" + npicpath + '\'' +
                ", nmodifydate=" + nmodifydate +
                ", nsummary='" + nsummary + '\'' +
                ", ncontent='" + ncontent + '\'' +
                ", comments=" + comments +
                '}';
    }
}