package com.edu.cn.mybatis.pojo;

public class Topic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.TID
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.TNAME
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    private String tname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.TID
     *
     * @return the value of topic.TID
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.TID
     *
     * @param tid the value for topic.TID
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.TNAME
     *
     * @return the value of topic.TNAME
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.TNAME
     *
     * @param tname the value for topic.TNAME
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }
}