package com.edu.cn.mybatis.pojo;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_users.uid
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_users.uname
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_users.upwd
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    private String upwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_users.uid
     *
     * @return the value of news_users.uid
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_users.uid
     *
     * @param uid the value for news_users.uid
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_users.uname
     *
     * @return the value of news_users.uname
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_users.uname
     *
     * @param uname the value for news_users.uname
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_users.upwd
     *
     * @return the value of news_users.upwd
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public String getUpwd() {
        return upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_users.upwd
     *
     * @param upwd the value for news_users.upwd
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    public void setUpwd(String upwd) {
        this.upwd = upwd == null ? null : upwd.trim();
    }
}