package com.edu.cn.mybatis.mapper;

import com.edu.cn.mybatis.pojo.Comment;
import java.util.List;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    Comment selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    List<Comment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comments
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    int updateByPrimaryKey(Comment record);
}