package com.edu.cn.mybatis.mapper;

import com.edu.cn.mybatis.pojo.Topic;
import java.util.List;

public interface TopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    int deleteByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    int insert(Topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    Topic selectByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    List<Topic> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    int updateByPrimaryKey(Topic record);
}