package com.edu.cn.mybatis.mapper;

import com.edu.cn.mybatis.pojo.User;
import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_users
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_users
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_users
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    User selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_users
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_users
     *
     * @mbggenerated Wed Mar 01 10:41:19 CST 2023
     */
    int updateByPrimaryKey(User record);
}